// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package com.ups.ship


case class Property(value: String,
  Key: String)


case class ClientInformationType(Property: com.ups.ship.Property*)


case class RequestType(RequestOption: Seq[String] = Nil,
  TransactionReference: Option[com.ups.ship.TransactionReferenceType] = None)


case class TransactionReferenceType(CustomerContext: Option[String] = None,
  TransactionIdentifier: Option[String] = None)


case class ResponseType(ResponseStatus: com.ups.ship.CodeDescriptionType,
  Alert: Seq[com.ups.ship.CodeDescriptionType] = Nil,
  TransactionReference: Option[com.ups.ship.TransactionReferenceType] = None)


case class CodeDescriptionType(Code: String,
  Description: String)

