// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package com.ups.ship


case class InternationalFormType(internationalformtypesequence1: com.ups.ship.InternationalFormTypeSequence1,
  internationalformtypesequence2: com.ups.ship.InternationalFormTypeSequence2,
  internationalformtypesequence3: com.ups.ship.InternationalFormTypeSequence3,
  internationalformtypesequence4: com.ups.ship.InternationalFormTypeSequence4) {
  lazy val FormType = internationalformtypesequence1.FormType
  lazy val UserCreatedForm = internationalformtypesequence1.UserCreatedForm
  lazy val AdditionalDocumentIndicator = internationalformtypesequence1.AdditionalDocumentIndicator
  lazy val FormGroupIdName = internationalformtypesequence1.FormGroupIdName
  lazy val SEDFilingOption = internationalformtypesequence1.SEDFilingOption
  lazy val Contacts = internationalformtypesequence1.Contacts
  lazy val Product = internationalformtypesequence1.Product
  lazy val InvoiceNumber = internationalformtypesequence1.InvoiceNumber
  lazy val InvoiceDate = internationalformtypesequence1.InvoiceDate
  lazy val PurchaseOrderNumber = internationalformtypesequence1.PurchaseOrderNumber
  lazy val TermsOfShipment = internationalformtypesequence2.TermsOfShipment
  lazy val ReasonForExport = internationalformtypesequence2.ReasonForExport
  lazy val Comments = internationalformtypesequence2.Comments
  lazy val DeclarationStatement = internationalformtypesequence2.DeclarationStatement
  lazy val Discount = internationalformtypesequence2.Discount
  lazy val FreightCharges = internationalformtypesequence2.FreightCharges
  lazy val InsuranceCharges = internationalformtypesequence2.InsuranceCharges
  lazy val OtherCharges = internationalformtypesequence2.OtherCharges
  lazy val CurrencyCode = internationalformtypesequence2.CurrencyCode
  lazy val BlanketPeriod = internationalformtypesequence2.BlanketPeriod
  lazy val ExportDate = internationalformtypesequence3.ExportDate
  lazy val ExportingCarrier = internationalformtypesequence3.ExportingCarrier
  lazy val CarrierID = internationalformtypesequence3.CarrierID
  lazy val InBondCode = internationalformtypesequence3.InBondCode
  lazy val EntryNumber = internationalformtypesequence3.EntryNumber
  lazy val PointOfOrigin = internationalformtypesequence3.PointOfOrigin
  lazy val ModeOfTransport = internationalformtypesequence3.ModeOfTransport
  lazy val PortOfExport = internationalformtypesequence3.PortOfExport
  lazy val PortOfUnloading = internationalformtypesequence3.PortOfUnloading
  lazy val LoadingPier = internationalformtypesequence3.LoadingPier
  lazy val PartiesToTransaction = internationalformtypesequence4.PartiesToTransaction
  lazy val RoutedExportTransactionIndicator = internationalformtypesequence4.RoutedExportTransactionIndicator
  lazy val ContainerizedIndicator = internationalformtypesequence4.ContainerizedIndicator
  lazy val License = internationalformtypesequence4.License
  lazy val ECCNNumber = internationalformtypesequence4.ECCNNumber
  lazy val OverridePaperlessIndicator = internationalformtypesequence4.OverridePaperlessIndicator
  lazy val ShipperMemo = internationalformtypesequence4.ShipperMemo
  lazy val MultiCurrencyInvoiceLineTotal = internationalformtypesequence4.MultiCurrencyInvoiceLineTotal
}


case class InternationalFormTypeSequence1(FormType: Seq[String] = Nil,
  UserCreatedForm: Option[com.ups.ship.UserCreatedFormType] = None,
  AdditionalDocumentIndicator: Option[String] = None,
  FormGroupIdName: Option[String] = None,
  SEDFilingOption: Option[String] = None,
  Contacts: Option[com.ups.ship.ContactType] = None,
  Product: Seq[com.ups.ship.ProductType] = Nil,
  InvoiceNumber: Option[String] = None,
  InvoiceDate: Option[String] = None,
  PurchaseOrderNumber: Option[String] = None)

case class InternationalFormTypeSequence2(TermsOfShipment: Option[String] = None,
  ReasonForExport: Option[String] = None,
  Comments: Option[String] = None,
  DeclarationStatement: Option[String] = None,
  Discount: Option[com.ups.ship.IFChargesType] = None,
  FreightCharges: Option[com.ups.ship.IFChargesType] = None,
  InsuranceCharges: Option[com.ups.ship.IFChargesType] = None,
  OtherCharges: Option[com.ups.ship.OtherChargesType] = None,
  CurrencyCode: String,
  BlanketPeriod: Option[com.ups.ship.BlanketPeriodType] = None)

case class InternationalFormTypeSequence3(ExportDate: Option[String] = None,
  ExportingCarrier: Option[String] = None,
  CarrierID: Option[String] = None,
  InBondCode: Option[String] = None,
  EntryNumber: Option[String] = None,
  PointOfOrigin: Option[String] = None,
  ModeOfTransport: Option[String] = None,
  PortOfExport: Option[String] = None,
  PortOfUnloading: Option[String] = None,
  LoadingPier: Option[String] = None)

case class InternationalFormTypeSequence4(PartiesToTransaction: Option[String] = None,
  RoutedExportTransactionIndicator: Option[String] = None,
  ContainerizedIndicator: Option[String] = None,
  License: Option[com.ups.ship.LicenseType] = None,
  ECCNNumber: Option[String] = None,
  OverridePaperlessIndicator: Option[String] = None,
  ShipperMemo: Option[String] = None,
  MultiCurrencyInvoiceLineTotal: Option[String] = None)


case class UserCreatedFormType(DocumentID: String*)


case class ContactType(ForwardAgent: Option[com.ups.ship.ForwardAgentType] = None,
  UltimateConsignee: Option[com.ups.ship.UltimateConsigneeType] = None,
  IntermediateConsignee: Option[com.ups.ship.IntermediateConsigneeType] = None,
  Producer: Option[com.ups.ship.ProducerType] = None,
  SoldTo: Option[com.ups.ship.SoldToType] = None)


case class ForwardAgentType(CompanyName: String,
  TaxIdentificationNumber: String,
  Address: com.ups.ship.AddressType)


case class AddressType(AddressLine: Seq[String] = Nil,
  City: String,
  StateProvinceCode: Option[String] = None,
  Town: Option[String] = None,
  PostalCode: Option[String] = None,
  CountryCode: String)


case class UltimateConsigneeType(CompanyName: String,
  Address: com.ups.ship.AddressType)


case class IntermediateConsigneeType(CompanyName: String,
  Address: com.ups.ship.AddressType)


case class ProducerType(Option: Option[String] = None,
  CompanyName: Option[String] = None,
  TaxIdentificationNumber: Option[String] = None,
  Address: Option[com.ups.ship.AddressType] = None,
  AttentionName: Option[String] = None,
  Phone: Option[com.ups.ship.PhoneType] = None,
  EMailAddress: Option[String] = None)


case class ProductType(Description: Seq[String] = Nil,
  Unit: Option[com.ups.ship.UnitType] = None,
  CommodityCode: Option[String] = None,
  PartNumber: Option[String] = None,
  OriginCountryCode: Option[String] = None,
  JointProductionIndicator: Option[String] = None,
  NetCostCode: Option[String] = None,
  NetCostDateRange: Option[com.ups.ship.NetCostDateType] = None,
  PreferenceCriteria: Option[String] = None,
  ProducerInfo: Option[String] = None,
  MarksAndNumbers: Option[String] = None,
  NumberOfPackagesPerCommodity: Option[String] = None,
  ProductWeight: Option[com.ups.ship.ProductWeightType] = None,
  VehicleID: Option[String] = None,
  ScheduleB: Option[com.ups.ship.ScheduleBType] = None,
  ExportType: Option[String] = None,
  SEDTotalValue: Option[String] = None,
  ExcludeFromForm: Option[com.ups.ship.ExcludeFromFormType] = None,
  ProductCurrencyCode: Option[String] = None,
  PackingListInfo: Option[com.ups.ship.PackingListInfoType] = None)


case class ExcludeFromFormType(FormType: String*)


case class UnitType(Number: String,
  UnitOfMeasurement: com.ups.ship.UnitOfMeasurementType,
  Value: String)


case class PackingListInfoType(PackageAssociated: com.ups.ship.PackageAssociatedType*)


case class PackageAssociatedType(PackageNumber: Option[String] = None,
  ProductAmount: Option[String] = None)


case class UnitOfMeasurementType(Code: String,
  Description: Option[String] = None)


case class NetCostDateType(BeginDate: String,
  EndDate: String)


case class ProductWeightType(UnitOfMeasurement: com.ups.ship.UnitOfMeasurementType,
  Weight: String)


case class ScheduleBType(Number: String,
  Quantity: Option[String] = None,
  UnitOfMeasurement: com.ups.ship.UnitOfMeasurementType)


case class IFChargesType(MonetaryValue: String)


case class OtherChargesType(MonetaryValue: String,
  Description: String)


case class BlanketPeriodType(BeginDate: String,
  EndDate: String)


case class LicenseType(Number: Option[String] = None,
  Date: Option[String] = None,
  ExceptionCode: Option[String] = None)


case class SoldToType(Name: String,
  AttentionName: String,
  TaxIdentificationNumber: Option[String] = None,
  Phone: Option[com.ups.ship.PhoneType] = None,
  Option: Option[String] = None,
  Address: com.ups.ship.AddressType,
  EMailAddress: Option[String] = None)


case class PhoneType(Number: String,
  Extension: Option[String] = None)

