// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package com.ups.ship


case class UsernameToken(Username: String,
  Password: String)


case class ServiceAccessToken(AccessLicenseNumber: String)


case class UPSSecurity(UsernameToken: com.ups.ship.UsernameToken,
  ServiceAccessToken: com.ups.ship.ServiceAccessToken)

